version: '3'

services:
  app:
  container_name: poetryc
    build: ./fastapi
    volumes:
      - ./fastapi:src
    ports:
      - "8000:8000"
    command: ["uvicorn", "healthcheck:app", "--reload", "--host", "0.0.0.0","--port","8000"]