version: '3'

services:
  app:
    container_name: poetryc-compose
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:8000"
    command: ["uvicorn", "healthcheck:app", "--reload", "--host", "0.0.0.0","--port","8000"]